name: Greeting workFlow
on: 
    push: 
        branches: 
            - main
jobs: 
    saluer: 
        runs-on: ubuntu-latest
        steps:
            - name: recuperer le repository
              uses: actions/checkout@v4
            - name: donner les permissions
              run: chmod +x ./scripts/salut.sh
            
            - name: executer les fichier salut
              run: ./scripts/salut.sh
    reponse: 
        runs-on: ubuntu-latest
        steps: 
            - name: Recuperer les ripository
              uses: actions/checkout@v4
            - name: donner les permissions
              run: chmod +x ./scripts/reponse.sh
            - name: executer les fichier response
              run: ./scripts/reponse.sh
        